[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r backend/hotel-santino-backend/requirements.txt"
]

[start]
cmd = "cd backend/hotel-santino-backend && uvicorn hotel:app --host 0.0.0.0 --port $PORT"

