/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eaedff",
        "surface-tint": "#0053db",
        "inverse-surface": "#283044",
        "on-secondary-fixed-variant": "#31447b",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-high": "#e2e7ff",
        "secondary": "#495c95",
        "inverse-primary": "#b4c5ff",
        "on-primary": "#ffffff",
        "background": "#faf8ff",
        "on-surface-variant": "#434655",
        "error": "#ba1a1a",
        "on-primary-fixed": "#00174b",
        "on-secondary": "#ffffff",
        "outline": "#737686",
        "primary-fixed-dim": "#b4c5ff",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c6d7",
        "on-primary-container": "#eeefff",
        "surface-container-low": "#f2f3ff",
        "on-secondary-container": "#394c84",
        "surface-variant": "#dae2fd",
        "primary": "#004ac6",
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "on-error": "#ffffff",
        "secondary-container": "#acbfff",
        "surface-container-highest": "#dae2fd",
        "surface-bright": "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "on-surface": "#131b2e",
        "error-container": "#ffdad6",
        "on-background": "#131b2e",
        "tertiary": "#943700",
        "primary-container": "#2563eb",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-secondary-fixed": "#00174b",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "sidebar": "#0f172a",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
